Repository ivario123/D0018E-e-comerce, pull requests merged in 2023-03, with the labels that each got.

#44 Admin product pages
  src/product.py
  src/sql/inventory/management.py
  static/js/inventory.js
  static/js/review.js
  templates/admin/index.html
  templates/admin/modify_product.html
  templates/base.html
  templates/product_info.html
Labels: BACKEND, FRONTEND

#42 User administration
  src/admin/__init__.py
  src/auth/internal.py
  src/models/item.py
  src/models/review.py
  src/product.py
  src/sql/inventory/getters.py
  src/sql/inventory/management.py
  src/user/__init__.py
  static/js/review.js
  templates/product_info.html
  templates/user/profile.html
Labels: HIGH, BACKEND, FRONTEND

#45 Dbv0.5
  database/V0.5/V0.5.mwb
  database/V0.5/V0.5.mwb.bak
  src/admin/__init__.py
  src/admin/internal.py
  src/app.py
  src/auth/__init__.py
  src/auth/internal.py
  src/examples/test1.json
  src/models/category.py
  src/models/review.py
  src/models/user.py
  src/order.py
  src/product.py
  src/sql/__init__.py
  src/sql/auth.py
  src/sql/inventory/getters.py
  src/sql/inventory/management.py
  static/js/category_management.js
  static/js/get_el.js
  static/js/inventory.js
  static/js/order.js
  static/js/review.js
  static/js/search.js
  static/js/sort.js
  templates/admin/create_category.html
  templates/admin/create_product.html
  templates/admin/index.html
  templates/admin/manage_categories.html
  templates/base.html
  templates/checkout.html
  templates/jinja_macros/cart.html
  templates/product_info.html
  templates/search.html
  templates/user/orders.html
Labels: DATABASE, BACKEND

#46 Order management
  src/admin/__init__.py
  src/sql/inventory/getters.py
  src/sql/inventory/management.py
  static/js/order.js
  templates/admin/index.html
  templates/admin/manage_orders.html
  templates/user/orders.html
Labels: DATABASE, BACKEND, FRONTEND

#48 Bug fixes
  src/sql/inventory/getters.py
  static/js/inventory.js
  templates/index.html
Labels: HIGH
