Repository ivario123/D0018E-e-comerce, pull requests merged in 2023-02, with the labels that each got.

#22 Johnny
  secrets/ssql.cfg
  src/app.py
  src/search.py
  src/sql/inventory/getters.py
  static/css/searchbar.css
  static/js/search.js
  templates/jinja_macros/navbar.html
Labels: HIGH, BLOCKING

#24 inital review structure
  src/app.py
  src/models/__init__.py
  src/models/item.py
  src/models/review.py
  src/product.py
  src/search.py
  src/sql/inventory/getters.py
  src/sql/inventory/management.py
  static/js/review.js
  templates/base.html
  templates/jinja_macros/form.html
  templates/jinja_macros/product_listing.html
  templates/product_info.html
Labels: MEDIUM, BACKEND, FRONTEND

#30 Prettier products
  src/sql/inventory/getters.py
  static/js/inventory.js
  templates/base.html
  templates/category.html
  templates/index.html
  templates/jinja_macros/product_listing.html
  templates/product_info.html
Labels: HIGH, FRONTEND

#31 Profile page
  src/app.py
  src/sql/auth.py
  src/user/__init__.py
  src/user/internal.py
  templates/jinja_macros/navbar.html
  templates/user/profile.html
Labels: DATABASE, FRONTEND

#29 Checkout
  database/V0.2/schema.sql
  database/V0.2/schematic.mwb
  database/V0.2/schematic.mwb.bak
  src/app.py
  src/models/order.py
  src/order.py
  src/product.py
  src/search.py
  src/sql/inventory/getters.py
  src/sql/inventory/management.py
  src/user/__init__.py
  static/js/login.js
  static/js/order.js
  static/js/search.js
  templates/base.html
  templates/checkout.html
  templates/jinja_macros/cart.html
  templates/jinja_macros/navbar.html
  templates/jinja_macros/product_listing.html
  templates/login.html
  templates/product_info.html
  templates/search.html
  templates/user/orders.html
Labels: HIGH, DATABASE, BACKEND, FRONTEND

#34 recomended products
  src/app.py
  src/sql/inventory/getters.py
  static/js/order.js
  templates/admin/create_product.html
  templates/admin/make_admin.html
  templates/index.html
  templates/jinja_macros/product_listing.html
Labels: MEDIUM, DATABASE, FRONTEND

#32 added sorting by attributes and filtering in search query
  src/search.py
  src/sql/inventory/getters.py
  static/js/search.js
  static/js/sort.js
  templates/category.html
  templates/index.html
  templates/jinja_macros/navbar.html
  templates/jinja_macros/product_listing.html
  templates/search.html
Labels: MEDIUM, DATABASE, BACKEND, FRONTEND

#35 prettier categories
  database/V0.3/schema.sql
  database/V0.3/v0.3.mwb
  src/admin/__init__.py
  src/admin/internal.py
  src/category.py
  src/sql/inventory/getters.py
  static/js/inventory.js
  templates/admin/create_category_group.html
  templates/category.html
Labels: FRONTEND
